name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Buildozer
        env:
          # Отключаем интерактивные запросы buildozer
          BUILDOZER_ALLOW_ROOT: 1
          # Подавляем все попытки ввода данных
          PYTHONUNBUFFERED: 1
        run: |
          # Используем --no-check-root и немедленно запускаем сборку
          buildozer --no-check-root android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
